### ISSUE TITLE
Anyway to limit the number of characters displayed?

### ISSUE THREAD

**Issue by ReMeDy-TV** [Bronya-Rand/Prome-VN-Extension#10]
I use several characters simultaneously in group chat that aren't necessarily involved in the group chat because it's simpler to just leave characters in the group chat rather than micromanaging them by removing and re-adding them.

It would be great if there were more customization options over how the sprites are handled, such as:

**a.)** Limit the number of sprites displayed to X where X equals the most recent sprites who have spoken.
**b.)** Limit the number of sprites displayed to X where X equals the sprites highest on the group chat order.
**c.)** Worst case scenario: Limit the sprite to just 1 and just load it in-and-out.

Another option could be an opacity value in the character tint menu, so that even if you can't adjust the amount of displayed characters, at least you can make the inactive ones hidden.

To show you how chaotic this can all get currently, look at what I've got here, lol.
![sprites](https://github.com/user-attachments/assets/4ea37797-96c5-4d4c-b9b5-431cc7378b36)

It's still an improvement over the default ST settings, since at least this extension darkens sprites that aren't speaking, so it's an improvement for that feature alone.

**Comment by ReMeDy-TV** [comment]
Okay, I found a work-around to recommend as a stop-gap: First, when a sprite is muted, their sprite vanishes, so any sprites not in the scene, mute them. For the sprites you actually envision to be in your scene, do not mute them, but rather set their Talkativeness setting to Shy on the far-left slider. This ensures they never talk unless you prompt them.

This allows the user to keep the sprites in the scene they want while removing sprites they don't want without literally deleting them off the members menu.

**Comment by Bronya-Rand** [comment]
I might be able to do something related to 1 based off the order of who has spoken? However I do have a slight concern it might not adjust all chars back to standard X size but I'll have to experiment and see.

**Comment by ReMeDy-TV** [comment]
I was thinking at first I may have found a work-around by doing a combination of muted sprites combined with unmuted sprites set to 0% Talkativeness slider. Problem is it still calls up the sprites when I mention characters directly by name, so that's not a good solution. (Edit: Oh, actually I had group reply strategy set to Natural order. If you set it to Manual, then this method does work. Nice!)

**Comment by Bronya-Rand** [comment]
Added
