### ISSUE TITLE
Moving the sprite ?

### ISSUE THREAD

**Issue by phenix60** [Bronya-Rand/Prome-VN-Extension#11]
I use the latest version of ST 1.12.9, with the latest version of the Prone vn-extension 1.1.3, in a solo chat, with the waifu mode activated and the "beta emulate character card as sprite", and it worked great, ( i mean by that it appear correctly) but then i wanted to move it slightly, the generated sprite from the character card, so i activate the MovingUI setting in ST, and tried to move the sprite but i couldn't as i dragged it, it got stuck in the left corner of my screen and couldn't move it then at all, so i had to reset the all UI to get it at its default position. ( which it not where i would want it to be)
Would there be a way to move the position of the sprite, or does its position is fixed..., i woul want to know if it possible to move it when we want and if so how ? or many you could add a slider or a way to move it in the settings of the Prone-VN-Extension.

**Comment by phenix60** [comment]
i'm sorry for this, yea i couldn't move it using the dot that appear on the top right of the element once i activate the movingUI setting in ST, but i didn't to adjust the size with the right arrow on the bottom right, which help me to adjust more like i wanted, but it still weird i could move the sprite using the upper right dot, so maybe you could into this but i got mostly what i wanted to do.

**Comment by Bronya-Rand** [comment]
Yeah so this isn't actually intended to be moved since not even solo chats has this option to be moveable at all. Will note it down as something to axe.

**Comment by Bronya-Rand** [comment]
What I can prob do is allow the ability to flip the order in a solo chat.

**Comment by Bronya-Rand** [comment]
Added
