### ISSUE TITLE
Group Validation is removing prome-user from the group

### ISSUE THREAD

**Issue by jadomingo** [Bronya-Rand/Prome-VN-Extension#8]
Tested with a group containing only a single Character. 

![image](https://github.com/user-attachments/assets/2465df29-aa7d-4730-acc0-1ea0eaec9d4f)

**Comment by Bronya-Rand** [comment]
PR #9 in a way may address this bug already but if not, for now, ignore it as this error is just ST "unable to find" the dummy char Prome made for your user sprites. Still will see if I can get rid of this if possible.
